# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:
let
  # default = 8080
  port = 8086;
in
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."termix" = {
    image = "ghcr.io/lukegus/termix:release-1.9.0";
    environment = {
      # "Enable_SLL" = "true";
      "PORT" = toString port;
      # "SSL_DOMAIN" = "termix.sua.sh";
    };
    volumes = [
      "termix_termix-data:/app/data:rw"
    ];
    ports = [
      "127.0.0.1:${toString port}:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=termix"
      "--network=termix_default"
    ];
  };
  # Networks
  systemd = {
    services = {
      "podman-termix" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-termix_default.service"
          "podman-volume-termix_termix-data.service"
        ];
        requires = [
          "podman-network-termix_default.service"
          "podman-volume-termix_termix-data.service"
        ];
        partOf = [
          "podman-compose-termix-root.target"
        ];
        wantedBy = [
          "podman-compose-termix-root.target"
        ];
      };

      "podman-network-termix_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f termix_default";
        };
        script = ''
          podman network inspect termix_default || podman network create termix_default
        '';
        partOf = [ "podman-compose-termix-root.target" ];
        wantedBy = [ "podman-compose-termix-root.target" ];
      };

      # Volumes
      "podman-volume-termix_termix-data" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect termix_termix-data || podman volume create termix_termix-data --driver=local
        '';
        partOf = [ "podman-compose-termix-root.target" ];
        wantedBy = [ "podman-compose-termix-root.target" ];
      };
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-termix-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
