# Auto-generated by compose2nix.
{ lib, config, ... }:
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."iSponsorBlockTV" = {
    image = "ghcr.io/dmunozv04/isponsorblocktv";
    volumes = [
      "/home/admin/isponsorblocktv:/app/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd = {
    services."podman-iSponsorBlockTV" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      partOf = [
        "podman-compose-isponsorblocktv-root.target"
      ];
      wantedBy = [
        "podman-compose-isponsorblocktv-root.target"
      ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-isponsorblocktv-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
