# Auto-generated by compose2nix.

{
  config,
  lib,
  pkgs,
  ...
}:
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."iSponsorBlockTV" = {
    image = "ghcr.io/dmunozv04/isponsorblocktv";
    volumes = [
      "isponsorblocktv_isponsorblocktv-data:/app/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };

  systemd = {
    services."podman-iSponsorBlockTV" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-volume-isponsorblocktv_isponsorblocktv-data.service"
      ];
      requires = [
        "podman-volume-isponsorblocktv_isponsorblocktv-data.service"
      ];
      partOf = [
        "podman-compose-isponsorblocktv-root.target"
      ];
      wantedBy = [
        "podman-compose-isponsorblocktv-root.target"
      ];
    };

    # Volumes
    services."podman-volume-isponsorblocktv_isponsorblocktv-data" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect isponsorblocktv_isponsorblocktv-data || podman volume create isponsorblocktv_isponsorblocktv-data --driver=local
      '';
      partOf = [ "podman-compose-isponsorblocktv-root.target" ];
      wantedBy = [ "podman-compose-isponsorblocktv-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-isponsorblocktv-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
