# Auto-generated by compose2nix.
{ lib, config, ... }:
{
  # Note: DNS firewall rule removed because this container uses --network=host
  # and doesn't need Podman's DNS service (aardvark-dns), which would conflict
  # with AdGuard Home already running on port 53.

  # Containers
  virtualisation.oci-containers.containers."iSponsorBlockTV" = {
    image = "ghcr.io/dmunozv04/isponsorblocktv";
    volumes = [
      "/home/admin/isponsorblocktv:/app/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd = {
    services."podman-iSponsorBlockTV" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      partOf = [
        "podman-compose-isponsorblocktv-root.target"
      ];
      wantedBy = [
        "podman-compose-isponsorblocktv-root.target"
      ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-isponsorblocktv-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
