# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."13ft" = {
    image = "ghcr.io/wasi-master/13ft:latest";
    ports = [
      "5001:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=13ft"
      "--network-alias=13ft"
      "--network=13ft_default"
    ];
  };
  systemd = {
    services."podman-13ft" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-13ft_default.service"
      ];
      requires = [
        "podman-network-13ft_default.service"
      ];
      partOf = [
        "podman-compose-13ft-root.target"
      ];
      wantedBy = [
        "podman-compose-13ft-root.target"
      ];
    };

    # Networks
    services."podman-network-13ft_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f 13ft_default";
      };
      script = ''
        podman network inspect 13ft_default || podman network create 13ft_default
      '';
      partOf = [ "podman-compose-13ft-root.target" ];
      wantedBy = [ "podman-compose-13ft-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-13ft-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
