# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}:
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."maloja-maloja" = {
    image = "krateng/maloja:3.2.4";
    environment = {
      "MALOJA_DATA_DIRECTORY" = "/data";
      "MALOJA_SKIP_SETUP" = "true";
    };
    volumes = [
      "maloja_maloja-data:/data:rw"
    ];
    ports = [
      "42010:42010/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=maloja"
      "--network=maloja_default"
    ];
  };
  systemd = {
    services = {
      "podman-maloja-maloja" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "no";
        };
        after = [
          "podman-network-maloja_default.service"
          "podman-volume-maloja_maloja-data.service"
        ];
        requires = [
          "podman-network-maloja_default.service"
          "podman-volume-maloja_maloja-data.service"
        ];
        partOf = [
          "podman-compose-maloja-root.target"
        ];
        wantedBy = [
          "podman-compose-maloja-root.target"
        ];
      };

      # Networks
      "podman-network-maloja_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f maloja_default";
        };
        script = ''
          podman network inspect maloja_default || podman network create maloja_default
        '';
        partOf = [ "podman-compose-maloja-root.target" ];
        wantedBy = [ "podman-compose-maloja-root.target" ];
      };

      # Volumes
      "podman-volume-maloja_maloja-data" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect maloja_maloja-data || podman volume create maloja_maloja-data --driver=local
        '';
        partOf = [ "podman-compose-maloja-root.target" ];
        wantedBy = [ "podman-compose-maloja-root.target" ];
      };
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-maloja-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
