# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}:
let
  # default = 3000
  port = 3006;
in
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."bentopdf" = {
    image = "ghcr.io/alam00000/bentopdf:v1.15.3";
    ports = [
      "${toString port}:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:8080\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--network-alias=bentopdf"
      "--network=bento_default"
    ];
  };

  # Networks
  systemd = {
    services."podman-bentopdf" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-bento_default.service"
      ];
      requires = [
        "podman-network-bento_default.service"
      ];
      partOf = [
        "podman-compose-bento-root.target"
      ];
      wantedBy = [
        "podman-compose-bento-root.target"
      ];
    };

    services."podman-network-bento_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f bento_default";
      };
      script = ''
        podman network inspect bento_default || podman network create bento_default
      '';
      partOf = [ "podman-compose-bento-root.target" ];
      wantedBy = [ "podman-compose-bento-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-bento-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
