# Auto-generated by compose2nix.
{
  config,
  lib,
  pkgs,
  infra,
  ...
}:
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  # Containers
  virtualisation.oci-containers.containers."organice" = {
    image = "twohundredok/organice:5873";
    environment = {
      "ORGANICE_WEBDAV_URL" = "https://organice.sua.dev/dav";
    };
    ports = [
      "127.0.0.1:${toString infra.ports.organice.app}:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=organice"
      "--network=organice_default"
    ];
  };
  systemd = {
    services."podman-organice" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-organice_default.service"
      ];
      requires = [
        "podman-network-organice_default.service"
      ];
      partOf = [
        "podman-compose-organice-root.target"
      ];
      wantedBy = [
        "podman-compose-organice-root.target"
      ];
    };

    # Networks
    services."podman-network-organice_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f organice_default";
      };
      script = ''
        podman network inspect organice_default || podman network create organice_default
      '';
      partOf = [ "podman-compose-organice-root.target" ];
      wantedBy = [ "podman-compose-organice-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-organice-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
