name: Build NixOS configurations
permissions:
  contents: read
on:
  push:
    paths:
      - "**/*.nix"
      - "**/*.yml"
      - "flake.lock"
      - "flake.nix"
  pull_request:
    paths:
      - "**/*.nix"
      - "**/*.yml"
      - "flake.lock"
      - "flake.nix"
jobs:
  build:
    runs-on: nix
    strategy:
      matrix:
        # Define each OS & configuration you want to build
        include:
          - config: lab
          - config: pi
      fail-fast: false # let all matrix jobs finish even if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Build ${{ matrix.config }}
        run: |
          nix develop --command just build ${{matrix.config}}
  build-home:
    runs-on: nix
    strategy:
      matrix:
        # Define each OS & configuration you want to build
        include:
          # - config: mbp3
          - config: penguin
      fail-fast: false # let all matrix jobs finish even if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Build ${{ matrix.config }}
        run: |
          nix develop --command just build-home ${{matrix.config}}
