name: Build & test NixOS/Darwin configurations
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Define each OS & configuration you want to build
        include:
          - os: ubuntu-latest
            system: nixos
            config: lab
          - os: ubuntu-24.04-arm
            system: nixos
            config: pi
          - os: macos-latest
            system: darwin
            config: mbp3
      fail-fast: false # let all matrix jobs finish even if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Flake check
        run: nix flake check
      - name: Build ${{ matrix.config }}
        run: |
          nix build -L .#${{ matrix.system }}Configurations.${{ matrix.config }}.config.system.build.toplevel
