{
  # toggle the relevant services from here
  imports = [
    ./13ft
    ./dashy
    ./it-tools
    ./samba
    ./syncthing
    ./termix
    ./ytdl-sub

    ./acme.nix
    ./actual.nix
    ./audiobookshelf.nix
    ./avahi.nix
    ./bazarr.nix
    ./calibre.nix
    ./fail2ban.nix
    ./gitea.nix
    ./glances.nix
    ./grafana.nix
    ./home-assistant.nix
    ./immich.nix
    ./jellyfin.nix
    ./lidarr.nix
    ./linkwarden.nix
    ./mealie.nix
    ./minecraft-server.nix
    ./navidrome.nix
    ./nginx.nix
    ./paperless.nix
    ./prometheus.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./readarr.nix
    ./searxng.nix
    ./smart.nix
    ./sonarr.nix
    ./stirling-pdf.nix
    ./vaultwarden.nix
    ./wastebin.nix
    ./wireguard.nix
  ];
}
