{
  # toggle the relevant services from here
  imports = [
    ./13ft
    ./dashy
    ./it-tools
    ./maloja
    ./nginx
    ./samba
    ./syncthing
    ./termix
    ./wireguard
    ./ytdl-sub

    ./acme.nix
    ./actual.nix
    ./audiobookshelf.nix
    ./avahi.nix
    ./calibre.nix
    ./fail2ban.nix
    ./firefox-syncserver.nix
    ./gitea.nix
    ./glances.nix
    ./grafana.nix
    ./home-assistant.nix
    ./hydra.nix
    ./immich.nix
    ./jellyfin.nix
    ./linkwarden.nix
    ./mealie.nix
    ./miniflux.nix
    ./navidrome.nix
    ./ollama.nix
    ./open-webui.nix
    ./paperless.nix
    ./prometheus.nix
    ./searxng.nix
    ./smart.nix
    ./stirling-pdf.nix
    ./vaultwarden.nix
    ./vscode-server.nix
    ./wastebin.nix
  ];
}
